// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaKgacsHulXMhYNTlqTYZVfyuVGuKzr6M',
    appId: '1:555351095456:web:1160ede66b11293234b1c5',
    messagingSenderId: '555351095456',
    projectId: 'mymessager-4b432',
    authDomain: 'mymessager-4b432.firebaseapp.com',
    storageBucket: 'mymessager-4b432.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4cabfKBW5oOKbJcM8UjC_Ur9fJV44AzQ',
    appId: '1:555351095456:android:ff2822ad2297d57434b1c5',
    messagingSenderId: '555351095456',
    projectId: 'mymessager-4b432',
    storageBucket: 'mymessager-4b432.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS5TG3RDna5_Yr-xbWpmUYlfff0CEeCWE',
    appId: '1:555351095456:ios:f00459a2190e73ad34b1c5',
    messagingSenderId: '555351095456',
    projectId: 'mymessager-4b432',
    storageBucket: 'mymessager-4b432.appspot.com',
    iosClientId:
        '555351095456-sdd4f5lmctg5al758tti5dke7hhpg25h.apps.googleusercontent.com',
    iosBundleId: 'com.example.mymessanger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS5TG3RDna5_Yr-xbWpmUYlfff0CEeCWE',
    appId: '1:555351095456:ios:c9a6a25f60f378e734b1c5',
    messagingSenderId: '555351095456',
    projectId: 'mymessager-4b432',
    storageBucket: 'mymessager-4b432.appspot.com',
    iosClientId:
        '555351095456-j69oc4bufk656ce33dhkckj80is015sb.apps.googleusercontent.com',
    iosBundleId: 'com.example.mymessanger.RunnerTests',
  );
}
